### PR TITLE
Metadata

### PR DESCRIPTION
**Pull request by cwytko**
We still have the blocking problem where the whole set up will wait for each sample to wait which will plug up the **live** run so I'll be fixing that next so we'll at least get partial results.
As it stands the process metadata provides symlinks to the experiments corresponding metadata files (found in the work directory)

### CODE REVIEW

**Comment by spficklin** [comment]
@cwytko can you fix the merge conflict and address @biggstd requested change as well?

**Comment by bentsherman** [comment]
I will test this branch soon on Palmetto when I have time...

**Comment by spficklin** [comment]
We might need to hold off on testing tihs @bentsherman .  @biggstd has a bit of a redo of the workflow using Docker images and fixing the timeout issues with NCBI which will affect how these metadata scripts behave.   Best to hold off for now.

**Comment by spficklin** [comment]
We'll have to merge these changes in after the docker rebuild of GEMmaker.

**Pull request closed without merging**
