### PR TITLE
Issue 115

### PR DESCRIPTION
**Pull request by JohnHadish**
Issue #115

Now implemented in main-e2e.nf

## Description

This changes the way data is staged. It will be slightly more work to run the example, but it will make more sense to the user in the long run. I have attempted to simplify the setup, while allowing the user to still take control of the structure if they know what they are doing.

New Structure:
```
// If you are following the example setup, you do not need to change these
    // parameters.
    reference_dir = "input/references/"
    input_data_dir = "input/"
    remote_sample_list = "SRA_IDs.txt"
    local_sample_files = "*_{1,2}.fastq"

    hisat2 {
      enable = false
      index_files = "*.ht2"
      gtf_file = "*.transcripts.gtf"
    }
    salmon {
      enable = true
      index_dir = "*.transcripts.Salmon.indexed"
    }
    kallisto {
      enable = false
      index_file = "*.transcripts.Kallisto.indexed"
    }
  }
```
The above example shows the parameters that the user can change, but they should not have to if they are following the example.

One issue that may arise is having multiple reference files in the reference directory. We will either have to make it clear that they should delete the example references before running it, or implement a check to make sure only one reference set is present.

What do you think? I wanted to make sure users still had control of the parameters if they wanted to, but that they could ignore them if they just wanted things to run. Do you think I left too many parameters, or not enough?

This has NOT been implemented in main.e2e as of yet, as I wanted to see what was thought of the new changes before I implemented it there as well.

## Testing?

To run the example, clone gemmaker and run these commands:
```
mkdir -p input
mv examples/CORG/* input

nextflow run main.nf -with-singularity

```

### CODE REVIEW

**Comment by spficklin** [comment]
In the current master branch each tool has it's own index parameter. 
https://github.com/SystemsGenetics/GEMmaker/blob/4d7a3d6cac6415977d362360b4352dbea15b0fab/nextflow.config#L35-L48

Can you use something similar?  For example for hisat2:
```
      index_dir = "${baseDir}/input/reference/indexes/hisat2"
```

**Comment by spficklin** [comment]
On second thought, how about just name `ht2_files` to `index_files` for consistency.

**Comment by JohnHadish** [comment]
Added fix to this, test the same as listed above. Also note, I updated the main-e2e.nf so that it is operational again and has consistent outputs with main.nf.

Now ready to be merged.

**Comment by spficklin** [comment]
Okay, I tested and it works!  Although, I did have to fix the directory structure for the input data. It seems to have not been pushed.  So, running the `main.nf` works.  But, I'm getting the following error when trying to run the `main-e2e.nf`:

```
N E X T F L O W  ~  version 19.07.0
Launching `main-e2e.nf` [fabulous_poisson] - revision: 13e656f1de
Script_3b6f8eb4: 479: unexpected char: '\' @ line 479, column 15.
           -l 70 \handleing
                 ^

1 error

```

**Comment by spficklin** [comment]
Also, the functionality to skip samples got munged when the master was merged into this branch so I fixed it.

**Comment by spficklin** [comment]
Now I'm getting this error on the e2e:

```
[b8/e600a7] process > retrieve_sra_metadata (1) [100%] 1 of 1 ✔
[05/972378] process > process_sample (2)        [100%] 10 of 10, failed: 9 ✔
[b4/2a7dca] process > multiqc                   [100%] 1 of 1 ✔
[26/a91340] process > create_gem                [100%] 1 of 1 ✔
[49/5478c3] NOTE: Process `process_sample (1)` terminated with an error exit status (1) -- Execution is retried (1)
[56/ec905e] NOTE: Process `process_sample (2)` terminated with an error exit status (1) -- Execution is retried (1)
[16/e5f95d] NOTE: Process `process_sample (3)` terminated with an error exit status (1) -- Execution is retried (1)
[c7/1962ad] NOTE: Process `process_sample (2)` terminated with an error exit status (1) -- Execution is retried (2)
[4f/4119a4] NOTE: Process `process_sample (1)` terminated with an error exit status (1) -- Execution is retried (2)
[7d/91e809] NOTE: Process `process_sample (3)` terminated with an error exit status (1) -- Execution is retried (2)
[6e/607167] NOTE: Process `process_sample (1)` terminated with an error exit status (1) -- Error is ignored
[fa/3d9b30] NOTE: Process `process_sample (3)` terminated with an error exit status (1) -- Error is ignored
[05/972378] NOTE: Process `process_sample (2)` terminated with an error exit status (1) -- Error is ignored
```
If I take out the ignore on failure I see this message:

```
Error executing process > 'process_sample (2)'

Caused by:
  Process `process_sample (2)` terminated with an error exit status (1)

Command executed:
  < script removed>

Command exit status:
  1

Command output:
  Analysis complete for 2_1.fastq

Command error:
  Started analysis of 2_1.fastq
```
It seemed to have worked, but the exit status is 1.

**Comment by JohnHadish** [comment]
Fixed, should work as expected now

**Comment by spficklin** [comment]
Works! Thanks.

**Pull request merged**
