### PR TITLE
Issue 38 docker integration

### PR DESCRIPTION
**Pull request by JohnHadish**
This pull request is integrating Docker into GEMmaker so that the user does not have to install all of the programs. NExtflow will automatically download and run the docker images from docker hub when using the tag “-profile inDocker”. It can also be run inSingularity using the tag “-profile inSingularity”

This also integrates the Docker for Salmon and Kallisto. 

Instructions for testing the docker integration:

Change the nextflow.config.example to nextflow.config, then run using inDocker and testing flags:
```
cp nextflow.config.example nextflow.config
nextflow run main.nf -profile inDocker,testing
```
This will run it with Hisat2

Now run with Kallisto by changing  “which alignment” to “1” in the “nextflow config”:
```
which_alignment = 1
```
Run with same flags as above, verify that it runs

Now run with Salmon by changing “which alignment” to “2” in the “nextflow config”:
```
which_alignment = 2
```
Run this third time, verify that it runs.

In addition, this pull has a new version of the Readme.md which is using ReadTheDocs format. This is not yet complete.

### CODE REVIEW

**Comment by bentsherman** [comment]
Okay, I'm just gonna go ahead and say, this PR is __WAY__ too big and there seem to be a lot of changes aside from the Docker integration. So if you could list any other intended changes aside from the Docker integration that would be helpful for me. I'm gonna go through this PR either way, but it may take some time for me to review and test everything.

**Comment by bentsherman** [comment]
Currently trying to clean up what I can to make the "Files Changed" tab easier to parse through.

Nextflow has built-in flags for running Docker / Singularity containers, so I updated the config file accordingly:
```bash
nextflow run main.nf -with-docker # -with-singularity
```

Is there a particular advantage to having separate Docker images for each software dependency? Why not just maintain a single Dockerfile? I feel like that would be much easier, and it should perform just as well if not better.

**Comment by bentsherman** [comment]
Well, everything looks great on my end! The Travis CI is working, I was able to use Docker on my local machine (including salmon and kallisto), and I can still use the workflow on Palmetto without Docker. As for Singularity, it seems to work on Palmetto without any configuration changes! I added an empty `singularity` block to the config just in case we need to add anything in the future. A few more notes:

- I'm still having that error with `fastq-dump` on Palmetto, but I don't think that's any cause for concern here since the local samples still get processed all the way through
- I changed the `python3scripts` Docker image to be just a `python` Docker image with python and python dependencies. It looks like GEMmaker can already use the python scripts from the host so we don't need to add the GEMmaker repo to the Docker image.
- **Someone needs to update all of the Docker images** on `systemsgenetics` DockerHub or configure Travis CI to do it because right now those `docker push` commands fail.

I'm pretty happy with everything now, you guys might want to test on Kamiak just to make sure the profile  still works. Every other environment should work fine.

**Comment by spficklin** [comment]
HI @bentsherman Thanks for checking.  Sorry that PR was so big.  We had a bit of confusion on our end that ended up with everyone's' changes in one large PR.  I sent you some messages on slack.  One of the changes you made was to put back the publish option mode.   That was changed specifically to 'symlink' so that the new cleanup processes would work.  I'd like to change it back.  But can you confirm there's no specific reason you need it that way on Palmetto?

**Comment by spficklin** [comment]
I just spoke with @bentsherman on Slack. I'm going to merge this in, and we'll fix the publish mode in another PR.

**Comment by spficklin** [comment]
Thanks @bentsherman for the review!

**Pull request merged**
