### PR TITLE
Fix for missing run

### PR DESCRIPTION
**Pull request by spficklin**
Issue #88 

## Description

the `retreive_sra_metadata.py` script had recently been changed to fix a problem with sending too many IDs to eutils at once.   That worked but it introduced another bug in that runs could be mapped to the wrong experiments and runs that were missing in the SRA database threw an error.  This fixes it. 

I've also added a unit testing script to test for this one problem again in the future.

## Testing?

Use the SRA ID `SRR2927685` in your SRA_IDs.txt file.  prior to this fix the script fails.  Afterwards it completes.

### CODE REVIEW

**Comment by bentsherman** [comment]
I moved the unit test to a new directory so that we can expand our unit tests in the future without clobbering the actual scripts. However the CI build is currently failing due to an issue with Aspera. The CI test runs successfully for me if I change `nextflow.config` to use the SRA toolkit instead. So while I think this PR is ready to merge, it looks like we need to deal with this Aspera failure in a separate thread.

**Comment by spficklin** [comment]
Once aspera (issue #91 ) is fixed we can revisit this pull request.

**Comment by spficklin** [comment]
Hi @bentsherman are these Travis CI fixes similar to those in PR #93 ?

**Comment by bentsherman** [comment]
Finally... got the unit test to work, the ascp bug seems to have disappeared (at least for the example data), and I think I fixed the duplicates issue (#92), so this PR is ready to merge on my end.

**Comment by bentsherman** [comment]
@spficklin no these changes are different from that PR.

**Pull request merged**
