### PR TITLE
nextflow.config clean up

### PR DESCRIPTION
**Pull request by biggstd**
## Description

Basically there were some default configuration variables for Docker that were not reasonable defaults. I moved those declarations to the profiles that used them. I also cleaned up the configuration file. This issue appeared to stem from the defaults set up for docker images. This required no changes to the `main.nf` file.

Some of the previous docker settings suggest that (on Palmetto, I assume) a Docker installation is not quite 'standard'. A `sudo` requirement indicates a normally recommended `docker` group is not available.

As an aside -- Ben was correct on the difference between `--with-docker` and `-with-docker`. Since anything can be a command line argument in Nextflow. While this works fine, I instead chose to move the `container.enabled = true` declaration to the various profiles that used them. The idea being that it is desirable to have all of the information that was used to run the workflow in a single 'unit', i.e., instead of needing a profile section and a terminal command to reproduce a run, only a profile section should be required.

### Local

```
nextflow run main.nf -profile testing
```

### Kamiak

The `slurm` profile will enable docker by default.

```
nextflow run main.nf -profile slurm
```

### Palmetto

I moved the old docker configuration to this profile, I hope the command
below works. This will now use docker by defualt.

```
nextflow run main.nf -profile pbs
```

### CODE REVIEW

**Comment by bentsherman** [comment]
After looking into it, I don't think any of these code changes have an effect on the ascp bug. In fact I was just able to run the example using ascp (both on my local machine and Palmetto) and it worked fine! I'm really beginning to suspect that something happened on the aspera / NCBI end that temporarily broke things, which is kind of scary...

**Comment by biggstd** [comment]
The bug (on Travis.ci at least) was caused by something in this old docker configuration:

```
    docker {
      enabled = true
      fixOwnership = true
      runOptions = "--init"
      sudo = true
    }
```

I think it may have been a permission error.

Per your suggestion I have spread back out some profiles. Although I am going to leave the travis profile, mostly for stability and possible future proofing. (We may move configs to separate files and use `includeConfig`)

The testing instructions then change to:

### Local

```
nextflow run main.nf -profile testing -with-docker
```

### Kamiak

The `slurm` profile with singularity.

```
nextflow run main.nf -profile slurm -with-singularity
```

### Palmetto

I moved the old docker configuration to this profile, I hope the command
below works. Since Palmetto appears(?) to require a specialized docker
configuration I created a new profile `pbs_docker`.


```
nextflow run main.nf -profile pbs,pbs_docker
```

**Comment by biggstd** [comment]
I just saw your new comment, Ben.

I recall (I hope correctly) that I observed this bug on my local machine depending if fixOwnership = false`.

The only other possibility aside from trouble on the aspera / NCBI would perhaps be issues or changes to Palmetto's Docker installation (seems unlikely).

**Comment by bentsherman** [comment]
As far as I can tell, these changes don't make a difference with regard to ascp. If you look at the latest commit on master you'll see that the CI test passes without any of the changes in this PR, and I'm no longer seeing the bug on my local machine. Even this PR right now -- two CI tests ran at the same time, one succeeded and one failed due to the transient error code 400. So I think this ascp bug may have been transient as well.

If you guys still want to merge these changes, that's kind of a separate conversation at this point. I'd have to look over the changes again, I think the pbs profile got messed up. By the way Palmetto uses Singularity just like Kamiak, not Docker.

**Comment by spficklin** [comment]
Okay, @biggstd since this PR does not fix the ascp issue can you rename this so that we don't get confused.  And as this seems to fix some Travis CI issues (right @biggstd) I think we don't necessarily need this for the v1.0 release.  I'll mark it for 1.1.

**Comment by biggstd** [comment]
@spficklin I've renamed this issue, although travis ci seems fine with the current docker configuration in `nextflow.config.example`, it does run in `sudo` by default, which is a painful default.

We should clean up this file though, there are unused declarations and config profiles that should be more cleanly separated (i.e. Lmod and docker in the same profile is meaningless).

We are also not quite using the profile sections as described in the documentation, this can prevent us from combining profiles in certain circumstances. For example, `params.execution` is (kind of) replicating the `executor` scope. 

We should also consider what it will take to add a reasonable `nextflow.config` file to this project, so that we could then run the entire thing from the terminal without cloning the repository.

**Comment by spficklin** [comment]
I'm a little confused now what state this PR is in.  Can someone summarize what this is actually fixing and if those fixes are completed?

**Comment by bentsherman** [comment]
@spficklin Yeah sorry I've been running around all day. I don't think this PR is _fixing_ anything anymore, now it's just a bunch of cleanup that Tyler and I have wanted to do to the config file. I was able to simplify some of the config code by using the new PBS Pro executor, for example.

@biggstd  I'm pretty happy with the changes at this point. I've adjusted my docker setup so that I can use it without sudo, I think that's a reasonable thing to assume in the config file. I also like having separate profiles for the environment modules, but I added a separate one for Palmetto because some of the module names differ.

My only remaining qualm I think is with the `travis` profile, I understand it's convenient for the travis script but I envision that eventually the travis CI will actually run nextflow multiple times with different configurations, and possibly different profiles. In fact we should probably use the same profiles in travis that we would use, like the `testing` profile, as a way to test the profiles themselves. So I still think we should get rid of that.

**Comment by spficklin** [comment]
Thanks @bentsherman for the clarification!  So, I'll not worry about this for the v1.0 release. If it makes it in then it makes it in.  The only request I have is that if we've changed the config file we also need to make sure the documentation is updated to reflect those changes. Would one of you be able to fix the docs as well?

**Comment by bentsherman** [comment]
@spficklin Done.

**Comment by spficklin** [comment]
So, before we merge this in.  How do these changes affect an existing v1.0 setup?  For example, if someone upgrades to v1.1 with these new additions how much of a change to their config file will they need to make?  Do the changes justify a 2.0 release rather than a v1.1?

**Comment by bentsherman** [comment]
No there aren't any breaking changes, I don't think users will need to change anything on their end.

**Comment by spficklin** [comment]
Thanks @biggstd and @bentsherman

**Pull request merged**
