### PR TITLE
Added multithreading option, other optimizations for Palmetto

### PR DESCRIPTION
**Pull request by bentsherman**
Default value is 1 for these options so as to not affect the WSU guys. Recommended value on Palmetto is 16 for each option.

Also increased `queueSize` to 1000 for PBS profile since we can do that on Palmetto.

### CODE REVIEW

**Comment by spficklin** [comment]
@cwytko can you please review this for @bentsherman

**Comment by bentsherman** [comment]
@cwytko If you haven't tested this PR yet, go ahead and wait for a bit because I have a few more changes to push. Working through some Palmetto-specific issues right now.

**Comment by bentsherman** [comment]
@cwytko it's ready to test now.

**Comment by cwytko** [comment]
@bentsherman go ahead and run the new commit on your end just to make sure that I didn't break anything on your end

**Comment by bentsherman** [comment]
I don't understand what you were trying to change, you have to do `cp nextflow.config.example nextflow.config` so that your `nextflow.config` is up to date. It looks like you just reverted a bunch of changes for no reason. Could you make your edits to nextflow.config.example and push that so that I can see what syntax errors you're talking about?

As for the nextflow version, we can just update the README.md to specify nextflow 0.32 since it's so easy to install.

**Comment by bentsherman** [comment]
Also, unless `NXF_VER=0.32.0 nextflow run ...` does not sound like a good idea, it will probably cause undefined behavior. You need to re-install nextflow to make sure you have the right version.

I can add a directive to `nextflow.config.example` to require nextflow >= 0.32.

**Comment by cwytko** [comment]
Ah I see I reverted all of the path/prefix parameters sorry about that I just did a regexp while looking at a stale commit.
I'll add the execution threads to the config example and remove tracking the `nextflow.config` as we do have the `nextflow.config.example` and specify a `manifest` for the `nextflowVersion`

**Comment by bentsherman** [comment]
@cwytko To make things easier I just overwrote your commit and pushed a few more changes that I needed to make. To get your local repo in order you can run the following:
```
git reset --hard 5a15b7c
git pull
```

**Pull request merged**
