### PR TITLE
Improvements for Kubernetes usage

### PR DESCRIPTION
**Pull request by bentsherman**
## Description
This PR is intended to make GEMmaker easier to use on Kubernetes, and hopefully easier to use in general as a by-product.

The main issue is that GEMmaker currently does not have a `nextflow.config` which can work out-of-the-box with real data. The user has to rename `nextflow.config.example` and change the input parameters to point to a custom directory instead of `examples`. What I have done follows the pattern I am using in KINC-nf and gene-oracle-nf: i define (1) an input directory and (2) relative paths to files that should be in the input directory. To run the example, you must copy files from `examples` into a new directory called `input`. However to transition to real data you must simply move the example data out and move the real data into the `input` directory. No changes to `nextflow.config` are required.

These changes should make it much easier to run GEMmaker via `nextflow run` and `nextflow kuberun` out-of-the-box. To make the example run easier, I have added a script called `tests/run-example.sh` which automatically stages the example data in the `input` directory.

## Testing?
Refer to travis CI results. You don't have to rename `nextflow.config.example` anymore because now it's just called `nextflow.config`.

### CODE REVIEW

**Comment by bentsherman** [comment]
Hmm, I guess there are still a couple of things that must be changed in `nextflow.config`: the reference prefix, and the project params although those aren't necessary. So I should say that this PR works _toward_ having a `nextflow.config` that works out of the box and is also flexible.

**Comment by spficklin** [comment]
Thanks @bentsherman just let us know when you're ready for us to test it.

**Comment by bentsherman** [comment]
Whoops forgot to test that one, it should be ready for you guys now.

**Comment by bentsherman** [comment]
@spficklin The CI build failed that time because one of the docker images failed to build, but this PR doesn't touch any of the Docker images. So if the example run works for you then I think it would be safe to merge.

**Comment by spficklin** [comment]
Hey @bentsherman this PR seems to still be failing on the CI check.  I looked at it and it seems to have completed to the end.  Can you see what's up with that?

**Comment by bentsherman** [comment]
@spficklin Refer to my previous comment.

**Comment by bentsherman** [comment]
@spficklin It works!

**Comment by spficklin** [comment]
@bentsherman one of the reasons we didn't have a `nextflow.config` was because if we made changes to it while development to suit our test run we run the risk of accidentally over riding the example setup.  Sometimes we have to test Nextflow on real data (not example data) and to do that we have to tweak the file.  So, I'm inclined to say we should move that file back to `nextflow.config.example`.

**Comment by bentsherman** [comment]
@spficklin Actually you shouldn't need to tweak the file much anymore, with these changes you would only have to change the reference prefix. Everything else is handled by moving data in and out of the `input` folder. I follow a similar practice for KINC and gene-oracle.

From a development perspective, there are drawbacks in either case. Yes you run the risk of commiting unwanted changes to `nextflow.config`, but with `nextflow.config.example` there is usually a lot of hassle involved in going back and forth between `nextflow.config` and `nextflow.config.example`. You have to work with `nextflow.config` while testing things, and then you have to update the example config but without the "tweaks" that you mentioned. So I don't think it's any more convenient from my experience.

From a user perspective, I think it's better to have a `nextflow.config` in the repo so that the user can run GEMaker out of the box easily. If they do `nextflow run systemsgenetics/GEMmaker`, or `nextflow kuberun systemsgenetics/GEMmaker`, the repo is pulled from Github and run automatically using `main.nf` and `nextflow.config`. This is also standard practice for nextflow pipelines in general, such as the ones on nf-core.

For these reasons I'd like to rename it to `nextflow.config`.

**Comment by JohnHadish** [comment]
I agree with Ben on the nextflow.config renaming. When teaching other people GEMmaker that were non-programmers, this was an issue that they ran into. We will just have to be careful when committing to Docker. 

My one issue with the input directory is that if users have local files on their machine, it may be a bit of a hassle to move large files to the input directory. The relative path idea that you have implemented makes things more logical for someone who is not familiar with the program, but I feel that we should make it very clear that you can still point to another directory. 

Also for the example, we should remove the example inputs from the ```example``` dir and just put the examples in the ```input``` dir. This will allow for the user to run the example as soon as they pull GEMmaker. Currently, the Travis CI moves the examples to the input dir. (GEMmaker should also come pulled with an input dir, otherwise user may be confused).

The Travis CI is working fine. I like all of the changes and approve the pull besides for the above suggestions.

**Comment by bentsherman** [comment]
@JohnHadish unfortunately there are issues with providing everything in the `input` directory by default as well. If the user does something like `nextflow run systemsgenetics/GEMmaker`, which is the conventional way to run a nextflow pipeline since you don't have to clone the repo explicitly, nextflow may or may not use this input directory depending on whether they use a custom nextflow config. The other issue is that there are actually two examples for CORG and ATH in separate sub-directories.

That being said, I think your point is valid and it would be nice to eliminate the extra copy step. At the same time, there is some sense in making the user explicitly stage the example input data, since they'll have to do that anyway with their real data. I think it would be best if we merge the PR as it is now, see how it goes, and come back to this in a separate PR if we want to.

**Comment by spficklin** [comment]
@bentsherman I think we need a deeper discussion about both issues for the config file and the input directory.  There are nuances to both of those changes that we should make sure we have sufficient ability to talk about.  Would it be possible to back out those to changes, then we can merge this PR and we can create a new issue for both of those.  Then in our next group meeting we can discuss them in more detail.

**Comment by bentsherman** [comment]
@spficklin I reverted the config file back to `nextflow.config.example`. As for the input directory, these changes are actually quite an integral part of this PR, such that removing them would essentially mean closing the PR, so I will leave them here. As it turns out, these changes are helpful for k8s usage but not urgent, so if you'd like to have a deeper discussion I think we can have it here.

**Comment by spficklin** [comment]
Well, I was hoping to get this PR out of the queue for you. It's been here for 21 days (too long).  I don't quite understand the purpose of the `input` directory.  I saw John's comments.  I think a Slack conversation might speed this up if you want to reach out to me there and help me understand.

**Comment by bentsherman** [comment]
I apologize, after looking at this PR more I think it's gotten pretty bloated. There are actually a few changes for k8s that are separate from this input directory issue so I will close this one and submit another PR with those changes. They should be easy to review and merge.

**Pull request closed without merging**
