### PR TITLE
Issue 110

### PR DESCRIPTION
**Pull request by JohnHadish**
Adds Cleaning Capabilities for Stringtie, Salmon, and Kallisto

Issue #110 

## Description

major changes:
- Clean ability Stringtie (ga, gtf files)
- Clean ability Salmon (ga file)
- Clean ability Kallisto (ga directory)

minor changes:
- Noticed that "clean_sam" had no on off switch (defaulted to always cleaning sam files). Added this functionality
- Rearranged the parameters in the nextflow-config to make it apparent that not all of them are used for each alignment option

## Code Changes

- Added new process for Salmon, Stringtie and Kallisto
- Removed process that created raw files for Hisat2 and merged this functionality into the fpkm, making it more consistent in code with Kallisto and Salmon
- Added additional template based off of "clean_files" that cleans directories (used by kallisto)

## Testing?

Run with Travis CI
Run example on local machine, see that files are removed when each parameter is turned to "false"  for each respective alignment tool

### CODE REVIEW

**Comment by spficklin** [comment]
@JohnHadish I tried testing. I set the `alignment = 1` for Kaliisto, and set `publish_gene_abundance = false` but it still published the gene abundance files:

```
./output/SRX218012/SRX218012_vs_CORG.ga/abundance.tsv
./output/SRX218012/SRX218012_vs_CORG.ga/abundance.h5
```
Are those not the abundance files that should be skipped?

**Comment by JohnHadish** [comment]
The files should still exist, but when you try to open them they should be empty. This is consistent with the rest of the workflow's cleanup design. We did this is so that nextflow can still restart.

**Comment by JohnHadish** [comment]
Oh, I see what you mean. The files are empty, but they should not be exported to the output. I will change that.

**Comment by JohnHadish** [comment]
Changed publishing option for Kallisto, Stringtie, and Salmon so that empty files are not seen in the output directory when `publish_gene_abundance = false`, and  `publish_stringtie_gtf_and_ga = false` respectively.

It should be noted that for MultiQC to work on Salmon, the log files must be stored in the directory tree structure:
```
*.ga/aux_info/meta_info.json
*.ga/libParams/flenDist.txt
```
For Kallisto to work with MultiQC, the standard output must be stored as a log file.

Stringtie does not output logfiles, so does not interact with MultiQC

**Comment by spficklin** [comment]
@JohnHadish do you need to do anything for the `main-e2e.nf` file?

**Comment by spficklin** [comment]
@JohnHadish I just went ahead and merged in support for the new options into the main-e2e file.  I'm testing now and I'll merge in a bit.

**Comment by spficklin** [comment]
Okay, all works. I tested on both main.nf and main-e2e.nf.  I'm merging.

**Pull request merged**
