### PR TITLE
Publish only output and log files, use a single output directory

### PR DESCRIPTION
**Pull request by bentsherman**
Also changed the default setting to use the directory structure outlined in the Google doc. I tested these changes by processing the first SRR in the unit test and i got this directory structure for the output:
```
$ find output | sort
output
output/report.html
output/SRX
output/SRX/10
output/SRX/10/36
output/SRX/10/36/SRX103665
output/SRX/10/36/SRX103665/SRX103665_1_fastqc.html
output/SRX/10/36/SRX103665/SRX103665_1_fastqc.zip
output/SRX/10/36/SRX103665/SRX103665_1p_trim_fastqc.html
output/SRX/10/36/SRX103665/SRX103665_1p_trim_fastqc.zip
output/SRX/10/36/SRX103665/SRX103665_1u_trim_fastqc.html
output/SRX/10/36/SRX103665/SRX103665_1u_trim_fastqc.zip
output/SRX/10/36/SRX103665/SRX103665_2_fastqc.html
output/SRX/10/36/SRX103665/SRX103665_2_fastqc.zip
output/SRX/10/36/SRX103665/SRX103665_2p_trim_fastqc.html
output/SRX/10/36/SRX103665/SRX103665_2p_trim_fastqc.zip
output/SRX/10/36/SRX103665/SRX103665_2u_trim_fastqc.html
output/SRX/10/36/SRX103665/SRX103665_2u_trim_fastqc.zip
output/SRX/10/36/SRX103665/SRX103665.trim.log
output/SRX/10/36/SRX103665/SRX103665_vs_TAIR10_Araport11.bam
output/SRX/10/36/SRX103665/SRX103665_vs_TAIR10_Araport11.bam.log
output/SRX/10/36/SRX103665/SRX103665_vs_TAIR10_Araport11.fpkm
output/SRX/10/36/SRX103665/SRX103665_vs_TAIR10_Araport11.sam.log
output/SRX/10/36/SRX103665/SRX103665_vs_TAIR10_Araport11.tpm
output/timeline.html
output/trace.txt
```

### CODE REVIEW

**Comment by spficklin** [comment]
@bentsherman can you provide some instructions that someone can follow to test this?

**Comment by bentsherman** [comment]
1. Change the unit test SRA file to have just the first SRR
2. Create `nextflow.config` from the example (and add the unit test settings)
3. Run nextflow: `nextflow run main.nf -profile slurm -with-report -with-timeline -with-trace`
4. Verify the output: `find output | sort`

**Comment by JohnHadish** [comment]
Hi Ben,
I was not able to run your pull request as it was. The issue I found was minor, but prevented operation. It does not seem related to this issue, but more related to GEMmaker not being tested on Kamiak (slurm cluster) before things are approved for the main branch. Therefore, the edit I am providing is not really related to this issue, but kind of a tag on that is just helping the main branch work on Kamiak again. 

When I ran your command after editing the nextflow.config, I get this error:
```
[john.hadish@login-p1n02 GEMmaker]$ nextflow run main.nf -profile slurm -with-report -with-timeline -with-trace
N E X T F L O W  ~  version 18.10.1
Launching `main.nf` [intergalactic_keller] - revision: 6aa8c54cef
ERROR ~ Unknown config attribute `process.withLabel:multithreaded.$` -- check config file: /home/john.hadish/GEMmaker/nextflow.config

 -- Check '.nextflow.log' file for details

```
When I go and look at the file it mentions, this is what I get:
```
Nov-15 09:45:14.590 [main] DEBUG nextflow.cli.Launcher - $> /data/ficklin/software/nextflow-18.10.1/nextflow run main.nf -profile slurm -with-report -with-timeline -with-trace
Nov-15 09:45:14.770 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 18.10.1
Nov-15 09:45:14.789 [main] INFO  nextflow.cli.CmdRun - Launching `main.nf` [intergalactic_keller] - revision: 6aa8c54cef
Nov-15 09:45:14.812 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /home/john.hadish/GEMmaker/nextflow.config
Nov-15 09:45:14.813 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/john.hadish/GEMmaker/nextflow.config
Nov-15 09:45:14.851 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `slurm`
Nov-15 09:45:15.526 [main] DEBUG nextflow.config.ConfigBuilder - In the following config object the attribute `process.withLabel:multithreaded.$` is empty:
  cpus=null
```
But when I look at the nextflow.config file, it appears that the cpus it mentions has an attribute:
```
slurm {
    process {
      executor = "slurm"
      queue = "ficklin"
      time = "4h"
      errorStrategy = "retry"
      maxRetries = "${params.execution.max_retries}"

      withLabel: "multithreaded" {
        cpus = ${params.execution.threads}
      }
      withLabel: "!multithreaded" {
        cpus = 1
      }
    }
    executor {
      queueSize = "${params.execution.queue_size}"
    }
  }
}
```

I figured out that the cpus parameter was missing quotation marks, which was preventing it from being run. I have made these changes, and submit my changes back to you. 

It should also be noted that I have also changed the nextflow.config.example back to the default of not putting it in the nested directory setting( ```sample_dir = { "${params.output.dir}/${sample_id}" }```) . The nested directories are kind of a special case, so should not be the default.

I like the output directory you added, it keeps everything nice and clean in the base directory.

Also, feel free to use the "RemoteRunExample" (located at ```GEMmaker/examples/RemoteRunExample``` in the future for tests like this, as it runs rather fast since it is a small file. It runs much faster than the arabidopsis data set you suggested for this test, and will generate an equivalent file set.


Cheers

**Comment by bentsherman** [comment]
Okay, I fixed some of your fixes, the `sample_dir` wasn't actually the original for some reason. In the future you can use the "files changed" tab to see the overall changes of the PR to catch things like that.

Sorry about the issue with Kamiak, eventually I'm going to use the new PbsProExecutor which will make the Palmetto config much more alike to the Kamiak config so issues like that won't come up. Also thanks for pointing out the remote example, totally forgot about that.

I think this branch is ready to merge, here's my test output with the remote example:
```
output
output/report.html
output/SRX218012
output/SRX218012/SRX218012_1_fastqc.html
output/SRX218012/SRX218012_1_fastqc.zip
output/SRX218012/SRX218012_1p_trim_fastqc.html
output/SRX218012/SRX218012_1p_trim_fastqc.zip
output/SRX218012/SRX218012_1u_trim_fastqc.html
output/SRX218012/SRX218012_1u_trim_fastqc.zip
output/SRX218012/SRX218012_2_fastqc.html
output/SRX218012/SRX218012_2_fastqc.zip
output/SRX218012/SRX218012_2p_trim_fastqc.html
output/SRX218012/SRX218012_2p_trim_fastqc.zip
output/SRX218012/SRX218012_2u_trim_fastqc.html
output/SRX218012/SRX218012_2u_trim_fastqc.zip
output/SRX218012/SRX218012.trim.log
output/SRX218012/SRX218012_vs_GCA_002793175.1_ASM279317v1_genomic.bam
output/SRX218012/SRX218012_vs_GCA_002793175.1_ASM279317v1_genomic.bam.log
output/SRX218012/SRX218012_vs_GCA_002793175.1_ASM279317v1_genomic.fpkm
output/SRX218012/SRX218012_vs_GCA_002793175.1_ASM279317v1_genomic.sam.log
output/SRX218012/SRX218012_vs_GCA_002793175.1_ASM279317v1_genomic.tpm
output/timeline.html
output/trace.txt
```

**Pull request merged**
